
CREATE TABLE CLIENTE (
                CLIENTE_ID INT NOT NULL,
                NOMBRE VARCHAR(75) NOT NULL,
                CORREO VARCHAR(100) NOT NULL,
                PIN INT NOT NULL,
                PRIMARY KEY (CLIENTE_ID)
);


CREATE TABLE PAGO_SUBSCRIPCION (
                PAGO_ID VARCHAR(50) NOT NULL,
                PRECIO INT NOT NULL,
                PERIODO VARCHAR(25) NOT NULL,
                CLIENTE_ID INT NOT NULL,
                PRIMARY KEY (PAGO_ID)
);


CREATE TABLE PERFIL_CLIENTE (
                PERFIL_ID VARCHAR(25) NOT NULL,
                NOMBRE_PERFIL VARCHAR(30) NOT NULL,
                CLIENTE_ID INT NOT NULL,
                PRIMARY KEY (PERFIL_ID)
);


CREATE TABLE CONTENIDO (
                CONTENIDO_ID INT NOT NULL,
                TITULO VARCHAR(75) NOT NULL,
                PERFIL_ID VARCHAR(25) NOT NULL,
                DURACION VARCHAR(100) NOT NULL,
                FECHA_LANSAMIENTO DATE NOT NULL,
                DESCRIPCION VARCHAR(500) NOT NULL,
                ELENCO VARCHAR(200) NOT NULL,
                PRIMARY KEY (CONTENIDO_ID)
);


ALTER TABLE PERFIL_CLIENTE ADD CONSTRAINT cliente_perfil_cliente_fk
FOREIGN KEY (CLIENTE_ID)
REFERENCES CLIENTE (CLIENTE_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PAGO_SUBSCRIPCION ADD CONSTRAINT cliente_pago_subscripcion_fk
FOREIGN KEY (CLIENTE_ID)
REFERENCES CLIENTE (CLIENTE_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE CONTENIDO ADD CONSTRAINT perfil_cliente_contenido_fk
FOREIGN KEY (PERFIL_ID)
REFERENCES PERFIL_CLIENTE (PERFIL_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;